Add script to verify that all files compile.
Useful to make sure things are happy before installing[1] and attempting
to run.

[1] My current workflow isn't ideal: instead of loading the development
environment I debug the 'installed' environment. I may get around to
figuring out a local::lib incantation or @INC tweak to fix that.

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! ./build/compile; then
+    echo "Code doesn't compile... Aborting.";
+    exit 1;
+fi;
+
 source build/rc;
 
 dist="$(get-dist)" || exit $?;
